name: Terraform CD (Apply-Manually)

on:
    workflow_dispatch: # üëà ejecuci√≥n manual desde GitHub UI
        inputs:
            environment:
                description: "Environment to deploy"
                required: true
                default: "dev"

jobs:
    terraform-apply:
        name: Terraform Apply
        runs-on: self-hosted # tu VM
        environment: production # üëà habilita approvals si quieres

        steps:
            # 1Ô∏è‚É£ Descargar c√≥digo
            - name: Checkout repository
              uses: actions/checkout@v4

            # 2Ô∏è‚É£ Instalar Terraform
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            # 3Ô∏è‚É£ Ver identidad AWS (control)
            - name: Verify AWS identity
              run: aws sts get-caller-identity

            # 4Ô∏è‚É£ Terraform Init
            - name: Terraform Init
              run: terraform init -input=false
              working-directory: envs/${{ inputs.environment }}

            # 5Ô∏è‚É£ Terraform Apply (MANUAL + sin auto-approve)
            - name: Terraform Apply
              run: terraform apply
              working-directory: envs/${{ inputs.environment }}
